version: 1.0.{build}

branches:
  only:
  - master

skip_tags: true
clone_folder: c:\projects\glcv

image:
  - Visual Studio 2017

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

platform: x64

build:
  parallel: true # enable MSBuild parallel builds
  verbosity: minimal

install:
  ############################################################################
  # All external dependencies are installed in C:\projects\deps
  ############################################################################
  - mkdir C:\projects\deps
  - cd C:\projects\deps

  ############################################################################
  # Install a recent CMake
  ############################################################################
  - set CMAKE_URL="https://cmake.org/files/v3.11/cmake-3.11.0-win64-x64.zip"
  - appveyor DownloadFile %CMAKE_URL% -FileName cmake.zip
  - 7z x cmake.zip -oC:\projects\deps > nul
  - move C:\projects\deps\cmake-* C:\projects\deps\cmake # Move to a version-agnostic directory
  - set PATH=C:\projects\deps\cmake\bin;%PATH%
  - cmake --version

  ############################################################################
  # Install Vulkan
  ############################################################################
  - set VULKAN_URL="https://sdk.lunarg.com/sdk/download/1.1.77.0/windows/VulkanSDK-1.1.77.0-Installer.exe?Human=true;u="
  - appveyor DownloadFile %VULKAN_URL% -FileName VulkanSDK.exe
  - .\VulkanSDK.exe /S
  - set VULKAN_SDK=c:\VulkanSDK\1.1.77.0

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cd C:\projects\glcv

build_script:
  - mkdir build
  - cd build
  - cmake ^
      -DGLCV_BUILD_TESTS=ON ^
      -DGLCV_BUILD_EXAMPLES=ON ^
      -DGLCV_USE_DEV_FLAGS=ON ^
      ..
  - cmake --build . --config %CONFIGURATION% -- /m

#test_script:
#  - ctest -C %CONFIGURATION%

notifications:
  - provider: Email
    to:
      - '{{commitAuthorEmail}}'
    on_build_failure: true
    on_build_success: false
